[project]
name = "galactic-trader"
version = "0.1.0"
description = "A turn-based space trading game"
readme = "README.md"
authors = [
    { name = "Spark2000", email = "paulalex.wetzel@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
galactic-trader = "galactic_trader.__main__:main"

[build-system]
requires = ["uv_build>=0.11.13,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "interrogate>=1.7.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.5",
]

[tool.pytest.ini_options]
addopts = """
-ra
--import-mode=importlib
--strict-config
--strict-markers
--doctest-modules
--cov=galactic_trader
--cov-branch
--cov-report=term-missing
"""
testpaths = [
    "tests",
    "src/galactic_trader",
]